package com.pims.entity;

import java.io.Serializable;
import java.util.Date;

public class Contract extends BaseBean implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.id
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.first_party
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private String firstParty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.second_party
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private String secondParty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.money
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.content
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.create_time
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.update_time
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.title
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.sign
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.status
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.id
     *
     * @return the value of contract.id
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.id
     *
     * @param id the value for contract.id
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.first_party
     *
     * @return the value of contract.first_party
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public String getFirstParty() {
        return firstParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.first_party
     *
     * @param firstParty the value for contract.first_party
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setFirstParty(String firstParty) {
        this.firstParty = firstParty == null ? null : firstParty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.second_party
     *
     * @return the value of contract.second_party
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public String getSecondParty() {
        return secondParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.second_party
     *
     * @param secondParty the value for contract.second_party
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setSecondParty(String secondParty) {
        this.secondParty = secondParty == null ? null : secondParty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.money
     *
     * @return the value of contract.money
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.money
     *
     * @param money the value for contract.money
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.content
     *
     * @return the value of contract.content
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.content
     *
     * @param content the value for contract.content
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.create_time
     *
     * @return the value of contract.create_time
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.create_time
     *
     * @param createTime the value for contract.create_time
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.update_time
     *
     * @return the value of contract.update_time
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.update_time
     *
     * @param updateTime the value for contract.update_time
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.title
     *
     * @return the value of contract.title
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.title
     *
     * @param title the value for contract.title
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.sign
     *
     * @return the value of contract.sign
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.sign
     *
     * @param sign the value for contract.sign
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.status
     *
     * @return the value of contract.status
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.status
     *
     * @param status the value for contract.status
     *
     * @mbg.generated Sat Jan 04 23:01:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}